## Session 2

In [2]:
import numpy as np

In [3]:
np.__version__

'2.2.5'

In [4]:
# Create an array filled with zeroes
zeroes = np.zeros(10, dtype=np.int32)

zeroes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [5]:
# Accessing elements using indexes
zeroes[2]

np.int32(0)

In [6]:
first_n = np.arange(9, dtype=np.int32)

first_n

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)

In [7]:
first_n[7]

np.int32(7)

In [8]:
# It is 1d array
first_n.shape

(9,)

In [9]:
# To make 2D array (3 x 3) array
first_n.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)

In [10]:
# But it is not assigned to first_n
first_n

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)

In [11]:
# To reflect the reshape changes, assign it
first_n = first_n.reshape(3,3)

first_n

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)

In [12]:
# Array of random integers in shape m, n
rand_n1 = np.random.randint(low=1, high=100, size=(5,5))

rand_n1

array([[81, 72, 46, 10, 10],
       [39, 11, 35, 17, 17],
       [ 9, 57,  1, 45, 44],
       [50,  3, 22, 15,  8],
       [94, 33, 48, 81, 43]], dtype=int32)

In [13]:
# There are many method for random for different scenarios
rand_n2 = np.random.random(size=(5,5))

rand_n2

array([[0.76691967, 0.27697096, 0.12820623, 0.63712753, 0.83726808],
       [0.82434861, 0.40608858, 0.23120673, 0.56153769, 0.29101511],
       [0.56992399, 0.26581327, 0.36287877, 0.66940964, 0.50801298],
       [0.10828474, 0.78573304, 0.63452398, 0.19777074, 0.20917929],
       [0.67287747, 0.45246621, 0.60076775, 0.04922034, 0.19660153]])

In [14]:
rand_n3 = np.random.rand(5,5)

rand_n3

array([[0.83184455, 0.79518687, 0.86247819, 0.19272414, 0.14360698],
       [0.19587724, 0.16952315, 0.09847815, 0.93041272, 0.13752091],
       [0.46287285, 0.10975087, 0.6577241 , 0.89848589, 0.16959788],
       [0.14221764, 0.0656776 , 0.01901896, 0.95350087, 0.14855975],
       [0.0552692 , 0.89274435, 0.64971384, 0.69702113, 0.19296908]])

In [15]:
rand_n4 = np.random.uniform(low=0, high=12, size=(3,4))

rand_n4

array([[6.66725666, 4.49135781, 0.26034433, 3.15877321],
       [8.41449937, 0.61922041, 2.72203612, 5.03498359],
       [5.55839562, 6.74136202, 3.26576482, 3.33328154]])

We have multiple methods to generate random elements

- randint(): method to generate random int elements with size of array with random value ranges from low to high

- random(): method to generate random float elements between 0 and 1 with size param which takes tuple to specify the dimension of array

- rand(): simple method which takes dimensions as params to generate nD array with random float elements between 0 and 1

- uniform(): creates a uniform distributiion between low and high with size of nd array

In [16]:
# We can take 1d array random and reshape using reshape()
rand_nums = np.random.rand(12)
rand_nums = rand_nums.reshape(3,4)
rand_nums

array([[0.95304188, 0.21656229, 0.73613937, 0.62804869],
       [0.34080063, 0.02950663, 0.69071967, 0.67143632],
       [0.91417274, 0.67332558, 0.38678946, 0.42210054]])

In [17]:
# To get diagonal matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# null values in numpy
print(np.nan)

print(0 * np.nan)

print(10 + np.nan)

print(np.nan == np.nan)

print(np.nan - np.nan)

nan
nan
nan
False
nan


In [19]:
# To get a infinite number
print(np.inf)

print(10000 < np.inf)

print(np.inf > np.nan)

print(np.inf < np.nan)

inf
True
False
False


In [20]:
# Some working of python interpreter/backend

print(0.3 == 3*0.1)

# It gives false because
print(3 * 0.1)

# If we round it
print(round(3 * 0.1, 1))
print(0.3 == round(3 * 0.1, 2))

False
0.30000000000000004
0.3
True


In [21]:
# To get a diagonal matrix
np.diag(np.arange(1,5))
# or
np.diag(1+np.arange(4))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [22]:
# To shift elements in diagonal matrix

# Shifting elements above diagonal
np.diag(np.arange(1,5), k=1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [23]:
# Shifting elements below diagonal
np.diag(np.arange(1,5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [24]:
# To get row and col index of nth elements
# For a 3x4 matrix the 5th element index is (1, 1)

np.unravel_index(5, (3,4))

(np.int64(1), np.int64(1))

In [25]:
# To get min and max values
rand_n1.min(), rand_n1.max()

(np.int32(1), np.int32(94))

In [26]:
np.min(rand_n1),np.max(rand_n1)

(np.int32(1), np.int32(94))

In [27]:
# Sum, mean
np.sum(rand_n1), np.mean(rand_n1), np.median(rand_n1)

(np.int64(891), np.float64(35.64), np.float64(35.0))

In [28]:
# Sorting nd array along no axis i.e, all elements
np.sort(rand_n1, axis=None, kind='quicksort')

array([ 1,  3,  8,  9, 10, 10, 11, 15, 17, 17, 22, 33, 35, 39, 43, 44, 45,
       46, 48, 50, 57, 72, 81, 81, 94], dtype=int32)

In [ ]:
# Sorting nd array along axis=1 i.e, cols
np.sort(rand_n1, axis=1, kind='quicksort')

array([[10, 10, 46, 72, 81],
       [11, 17, 17, 35, 39],
       [ 1,  9, 44, 45, 57],
       [ 3,  8, 15, 22, 50],
       [33, 43, 48, 81, 94]], dtype=int32)

In [ ]:
# Sorting nd array along axis=0 i.e, rows
np.sort(rand_n1, axis=0, kind='quicksort')

array([[ 9,  3,  1, 10,  8],
       [39, 11, 22, 15, 10],
       [50, 33, 35, 17, 17],
       [81, 57, 46, 45, 43],
       [94, 72, 48, 81, 44]], dtype=int32)

In [31]:
rand_n1 - rand_n1.min()

array([[80, 71, 45,  9,  9],
       [38, 10, 34, 16, 16],
       [ 8, 56,  0, 44, 43],
       [49,  2, 21, 14,  7],
       [93, 32, 47, 80, 42]], dtype=int32)

In [32]:
arr1 = np.random.randint(1, 6, (3,4))
arr2 = np.random.randint(1, 6, (4,3))

In [33]:
arr1, arr2

(array([[4, 3, 2, 1],
        [1, 5, 2, 5],
        [5, 1, 1, 1]], dtype=int32),
 array([[4, 5, 1],
        [5, 1, 2],
        [4, 4, 1],
        [4, 1, 4]], dtype=int32))

In [34]:
np.dot(arr1, arr2)

array([[43, 32, 16],
       [57, 23, 33],
       [33, 31, 12]], dtype=int32)

In [35]:
arr1 @ arr2

array([[43, 32, 16],
       [57, 23, 33],
       [33, 31, 12]], dtype=int32)

In [36]:
# To get elements more than 5
nd_arr = np.random.random(size=(5,5))
nd_arr

array([[0.57631359, 0.32366819, 0.64644303, 0.50458884, 0.80711457],
       [0.73333731, 0.37042046, 0.49027249, 0.97080002, 0.89402503],
       [0.43379453, 0.33297491, 0.94184892, 0.79064771, 0.64382412],
       [0.25275278, 0.33049115, 0.66198327, 0.63758205, 0.68161915],
       [0.00853036, 0.94985523, 0.93002806, 0.02264199, 0.43168341]])

In [37]:
# Manual iterating using loops

%time
for row in range(nd_arr.shape[0]):
    for col in range(nd_arr.shape[1]):
        if nd_arr[row][col] > 0.5:
            print(True, end=' ')
        else:
            print(False, end=' ')
    print()

CPU times: total: 0 ns
Wall time: 0 ns
True False True True True 
True False False True True 
False False True True True 
False False True True True 
False True True False False 


In [38]:
# Using np
%time
~(nd_arr > 0.5)

CPU times: total: 0 ns
Wall time: 0 ns


array([[False,  True, False, False, False],
       [False,  True,  True, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True, False, False,  True,  True]])

In [39]:
# To get/filters values of those elements
nd_arr[~(nd_arr < 0.5)]

array([0.57631359, 0.64644303, 0.50458884, 0.80711457, 0.73333731,
       0.97080002, 0.89402503, 0.94184892, 0.79064771, 0.64382412,
       0.66198327, 0.63758205, 0.68161915, 0.94985523, 0.93002806])

In [40]:
# Multiple values whereever there are <0.5
%time
nd_arr[~(nd_arr > 0.5)] = nd_arr[~(nd_arr > 0.5)] * 10
nd_arr

CPU times: total: 0 ns
Wall time: 0 ns


array([[0.57631359, 3.23668188, 0.64644303, 0.50458884, 0.80711457],
       [0.73333731, 3.70420457, 4.90272485, 0.97080002, 0.89402503],
       [4.33794534, 3.32974911, 0.94184892, 0.79064771, 0.64382412],
       [2.52752781, 3.30491146, 0.66198327, 0.63758205, 0.68161915],
       [0.08530361, 0.94985523, 0.93002806, 0.22641987, 4.31683408]])

In [41]:
%time
np.where(~(nd_arr < 0.5), nd_arr * 10, nd_arr)

CPU times: total: 0 ns
Wall time: 0 ns


array([[ 5.76313594, 32.36681878,  6.46443032,  5.04588844,  8.07114575],
       [ 7.33337309, 37.04204571, 49.02724853,  9.70800019,  8.94025031],
       [43.37945345, 33.29749109,  9.41848918,  7.90647709,  6.43824121],
       [25.27527808, 33.04911459,  6.61983271,  6.37582052,  6.81619152],
       [ 0.08530361,  9.49855234,  9.30028064,  0.22641987, 43.16834079]])

In [52]:
nd_arr1 = np.random.randint(1000, 9999, (20, 20))
nd_arr2 = np.random.randint(1000, 9999, (20, 20))
avg_val1 = np.mean(nd_arr1)
avg_val2 = np.mean(nd_arr2)

In [53]:
%time
nd_arr1[nd_arr1 < avg_val1] = avg_val2

CPU times: total: 0 ns
Wall time: 0 ns


In [54]:
%time
np.where(nd_arr1 < avg_val1, avg_val2, nd_arr1)

CPU times: total: 0 ns
Wall time: 0 ns


array([[5600., 8006., 6594., 5593., 5600., 6297., 7779., 6920., 5600.,
        6624., 5600., 5600., 8377., 5600., 5600., 7601., 5600., 5600.,
        9274., 5600.],
       [5600., 6932., 5600., 5991., 5600., 7037., 5600., 5600., 5600.,
        6898., 5600., 5469., 5600., 8066., 5600., 6501., 8209., 7874.,
        5600., 5600.],
       [5600., 5487., 5699., 5600., 5600., 5620., 5600., 5600., 6511.,
        6649., 5600., 5813., 6835., 5600., 6837., 5600., 5600., 5600.,
        8617., 7095.],
       [5600., 6031., 5600., 5600., 5600., 5600., 5600., 5600., 9867.,
        5600., 5364., 5600., 5600., 9230., 8812., 6560., 5600., 5600.,
        5600., 5481.],
       [5600., 5600., 8691., 5600., 5600., 5600., 5600., 5600., 9667.,
        8036., 8292., 8480., 5600., 9776., 5600., 7394., 5600., 5600.,
        5600., 5600.],
       [6112., 6436., 9313., 5600., 6629., 5600., 5778., 8046., 5600.,
        6897., 5600., 5600., 5836., 9646., 9199., 9870., 5600., 5600.,
        7428., 7367.],
       [88