In [6]:
import numpy as np
import pandas as pd

In [7]:
# To get sum of elements in array
int_arr = np.random.randint(1, 10, (3,3))
int_arr

array([[1, 2, 6],
       [8, 9, 1],
       [9, 8, 5]], dtype=int32)

In [8]:
np.sum(int_arr)

np.int64(49)

In [9]:
# Sum along cols
np.sum(int_arr, axis=1)

array([ 9, 18, 22])

In [10]:
# Sum along rows
np.sum(int_arr, axis=0)

array([18, 19, 12])

In [11]:
# To check if all elements of 2 array are equal
int_arr1 = np.random.randint(1, 10, (3,3))
int_arr2 = np.random.randint(1, 10, (3,3))

np.allclose(int_arr1, int_arr1)

True

In [12]:
int_arr.shape

(3, 3)

In [13]:
int_arr.dtype

dtype('int32')

In [14]:
int_arr.astype(np.int16)

array([[1, 2, 6],
       [8, 9, 1],
       [9, 8, 5]], dtype=int16)

In [15]:
np.mean(int_arr)

np.float64(5.444444444444445)

In [16]:
np.mean(int_arr, axis=1)

array([3.        , 6.        , 7.33333333])

In [17]:
np.mean(int_arr, axis=1, keepdims=True)

array([[3.        ],
       [6.        ],
       [7.33333333]])

In [18]:
np.isnan(int_arr)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [19]:
np.isnan(int_arr).any()

np.False_

In [20]:
np.isnan(int_arr).sum()

np.int64(0)

In [21]:
np.isnan(int_arr).any().sum()

np.int64(0)

In [22]:
np.sum(np.isnan(int_arr)), np.sum(np.isnan(int_arr), axis=1), np.sum(np.isnan(int_arr), axis=0)

(np.int64(0), array([0, 0, 0]), array([0, 0, 0]))

In [23]:
np.ones((3,2), dtype=np.int16)

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int16)

In [24]:
np.ones((3,2), dtype=np.bool)

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [25]:
int_arr

array([[1, 2, 6],
       [8, 9, 1],
       [9, 8, 5]], dtype=int32)

In [26]:
np.concat((int_arr, int_arr))

array([[1, 2, 6],
       [8, 9, 1],
       [9, 8, 5],
       [1, 2, 6],
       [8, 9, 1],
       [9, 8, 5]], dtype=int32)

In [27]:
np.hstack((int_arr, int_arr))

array([[1, 2, 6, 1, 2, 6],
       [8, 9, 1, 8, 9, 1],
       [9, 8, 5, 9, 8, 5]], dtype=int32)

In [28]:
np.vstack((int_arr, int_arr))

array([[1, 2, 6],
       [8, 9, 1],
       [9, 8, 5],
       [1, 2, 6],
       [8, 9, 1],
       [9, 8, 5]], dtype=int32)

In [29]:
np.intersect1d(int_arr1, int_arr2)

array([2, 5, 6, 7], dtype=int32)

# Pandas

In [291]:
pd.__version__

'2.2.3'

In [292]:
s = pd.Series([1,2,3,4,5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [293]:
data = pd.read_csv('Titanic-Dataset.csv')
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [294]:
data.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [295]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [296]:
data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [297]:
data.shape

(891, 12)

In [298]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [299]:
my_arr = np.random.random((10, 5))

df = pd.DataFrame(my_arr, columns=['A', 'B', 'C', 'D', 'E'])
df

A         B         C         D         E
0  0.793924  0.284918  0.670411  0.004255  0.629787
1  0.900960  0.997951  0.395181  0.590617  0.567996
2  0.326159  0.299136  0.243361  0.561871  0.576709
3  0.529260  0.384669  0.192945  0.012434  0.042155
4  0.630137  0.891938  0.361144  0.208947  0.850944
5  0.710595  0.794320  0.695870  0.362609  0.650522
6  0.192097  0.945624  0.107164  0.817429  0.674483
7  0.539932  0.635578  0.754428  0.758634  0.868931
8  0.143976  0.084239  0.348389  0.455470  0.820291
9  0.255857  0.687899  0.328189  0.286331  0.524713

In [300]:
mydict = {
	'Name': ['Sam', 'Pam', 'Suresh', 'Yasmin', 'Gopal'],
	'Age': [23,34,19,31,36],
	'Salary': np.random.randint(5000,8500,5),
	'Country': ['Canada', 'USA', 'India', None, 'Mexico'],
    'mob_num': [98, 98, 34, 12, None]
}

In [301]:
mydict.keys()

dict_keys(['Name', 'Age', 'Salary', 'Country', 'mob_num'])

In [302]:
mydict.values()

dict_values([['Sam', 'Pam', 'Suresh', 'Yasmin', 'Gopal'], [23, 34, 19, 31, 36], array([8383, 7593, 6121, 6662, 6513], dtype=int32), ['Canada', 'USA', 'India', None, 'Mexico'], [98, 98, 34, 12, None]])

In [303]:
mydict.items()

dict_items([('Name', ['Sam', 'Pam', 'Suresh', 'Yasmin', 'Gopal']), ('Age', [23, 34, 19, 31, 36]), ('Salary', array([8383, 7593, 6121, 6662, 6513], dtype=int32)), ('Country', ['Canada', 'USA', 'India', None, 'Mexico']), ('mob_num', [98, 98, 34, 12, None])])

In [304]:
mydict['Name']

['Sam', 'Pam', 'Suresh', 'Yasmin', 'Gopal']

In [305]:
mydict.get('Name')

['Sam', 'Pam', 'Suresh', 'Yasmin', 'Gopal']

In [306]:
mydict

{'Name': ['Sam', 'Pam', 'Suresh', 'Yasmin', 'Gopal'],
 'Age': [23, 34, 19, 31, 36],
 'Salary': array([8383, 7593, 6121, 6662, 6513], dtype=int32),
 'Country': ['Canada', 'USA', 'India', None, 'Mexico'],
 'mob_num': [98, 98, 34, 12, None]}

In [307]:
mydf = pd.DataFrame(mydict)
mydf

Name  Age  Salary Country  mob_num
0     Sam   23    8383  Canada     98.0
1     Pam   34    7593     USA     98.0
2  Suresh   19    6121   India     34.0
3  Yasmin   31    6662    None     12.0
4   Gopal   36    6513  Mexico      NaN

In [308]:
mydf.isna().any()

Name       False
Age        False
Salary     False
Country     True
mob_num     True
dtype: bool

In [309]:
mydf.isna().sum()

Name       0
Age        0
Salary     0
Country    1
mob_num    1
dtype: int64

In [310]:
mydf.Country.isna().any()

np.True_

In [311]:
mydf[1:4]

Name  Age  Salary Country  mob_num
1     Pam   34    7593     USA     98.0
2  Suresh   19    6121   India     34.0
3  Yasmin   31    6662    None     12.0

In [312]:
mydf[3:]

Name  Age  Salary Country  mob_num
3  Yasmin   31    6662    None     12.0
4   Gopal   36    6513  Mexico      NaN

In [313]:
mydf[::-1]

Name  Age  Salary Country  mob_num
4   Gopal   36    6513  Mexico      NaN
3  Yasmin   31    6662    None     12.0
2  Suresh   19    6121   India     34.0
1     Pam   34    7593     USA     98.0
0     Sam   23    8383  Canada     98.0

In [314]:
list(mydf.index)

[0, 1, 2, 3, 4]

In [315]:
idx = ['zero', 'one', 'two', 'three', 'four']
mydf.index = idx
mydf

Name  Age  Salary Country  mob_num
zero      Sam   23    8383  Canada     98.0
one       Pam   34    7593     USA     98.0
two    Suresh   19    6121   India     34.0
three  Yasmin   31    6662    None     12.0
four    Gopal   36    6513  Mexico      NaN

In [316]:
mydf.index = mydf.Country
mydf

Name  Age  Salary Country  mob_num
Country                                      
Canada      Sam   23    8383  Canada     98.0
USA         Pam   34    7593     USA     98.0
India    Suresh   19    6121   India     34.0
None     Yasmin   31    6662    None     12.0
Mexico    Gopal   36    6513  Mexico      NaN

In [317]:
mydf.reset_index(drop=True, inplace=True)
mydf

Name  Age  Salary Country  mob_num
0     Sam   23    8383  Canada     98.0
1     Pam   34    7593     USA     98.0
2  Suresh   19    6121   India     34.0
3  Yasmin   31    6662    None     12.0
4   Gopal   36    6513  Mexico      NaN

In [318]:
mydf.index = idx
mydf.reset_index(drop=False, inplace=True)
mydf

index    Name  Age  Salary Country  mob_num
0   zero     Sam   23    8383  Canada     98.0
1    one     Pam   34    7593     USA     98.0
2    two  Suresh   19    6121   India     34.0
3  three  Yasmin   31    6662    None     12.0
4   four   Gopal   36    6513  Mexico      NaN

In [319]:
mydf.drop(columns='index', inplace=True)
mydf

Name  Age  Salary Country  mob_num
0     Sam   23    8383  Canada     98.0
1     Pam   34    7593     USA     98.0
2  Suresh   19    6121   India     34.0
3  Yasmin   31    6662    None     12.0
4   Gopal   36    6513  Mexico      NaN

In [320]:
mydf

Name  Age  Salary Country  mob_num
0     Sam   23    8383  Canada     98.0
1     Pam   34    7593     USA     98.0
2  Suresh   19    6121   India     34.0
3  Yasmin   31    6662    None     12.0
4   Gopal   36    6513  Mexico      NaN

In [321]:
mydf[['Name']]

Name
0     Sam
1     Pam
2  Suresh
3  Yasmin
4   Gopal

In [322]:
mydf.Name

0       Sam
1       Pam
2    Suresh
3    Yasmin
4     Gopal
Name: Name, dtype: object

In [323]:
cols = ['Name', 'Country']
mydf[cols]

Name Country
0     Sam  Canada
1     Pam     USA
2  Suresh   India
3  Yasmin    None
4   Gopal  Mexico

In [324]:
# Get name and salary whose age is 28 and mob no is 98.0
cols = ['Name', 'Salary']

filter1 = mydf.Age == 34
filter2 = mydf.mob_num == 98.0

mydf[filter1 & filter2][cols]

Name  Salary
1  Pam    7593

In [325]:
mydf.where((mydf.Age == 34) & (mydf.mob_num == 98.0)).dropna()[cols]

Name  Salary
1  Pam  7593.0

In [326]:
mydf.where((mydf.Age == 34) & (mydf.mob_num == 98.0)).dropna().filter(items=cols)

Name  Salary
1  Pam  7593.0

In [327]:
mydf[filter1 | filter2][cols]

Name  Salary
0  Sam    8383
1  Pam    7593

# loc and iloc

loc: lable-based indexing, Uses labels to index the rows and cols in dataframe

iloc: integer-location based indexing, Uses integers to index the rows and cols in dataframe

In [328]:
mydf.loc[0:2,['Name', 'Age']]

Name  Age
0     Sam   23
1     Pam   34
2  Suresh   19

In [329]:
mydf.iloc[0:3, 1:3]

Age  Salary
0   23    8383
1   34    7593
2   19    6121

In [330]:
mydf.index = idx
mydf

Name  Age  Salary Country  mob_num
zero      Sam   23    8383  Canada     98.0
one       Pam   34    7593     USA     98.0
two    Suresh   19    6121   India     34.0
three  Yasmin   31    6662    None     12.0
four    Gopal   36    6513  Mexico      NaN

In [331]:
mydf.loc['zero':'two', cols]

Name  Salary
zero     Sam    8383
one      Pam    7593
two   Suresh    6121

In [332]:
mydf.iloc[0:3, 1:3]

Age  Salary
zero   23    8383
one    34    7593
two    19    6121

In [333]:
mydf.iloc[0:3, [1,3]]

Age Country
zero   23  Canada
one    34     USA
two    19   India

In [334]:
mydf.iloc[0:3, [-1]]

mob_num
zero     98.0
one      98.0
two      34.0

In [335]:
mydf.iloc[0:3, -3:-1]

Salary Country
zero    8383  Canada
one     7593     USA
two     6121   India

In [228]:
mydf.drop(columns='Adult', inplace=True)

KeyError: "['Adult'] not found in axis"

In [ ]:
mydf.drop(columns='mob_num_updated', inplace=True)

In [ ]:
mydf.loc[mydf.Age>30,'Adult'] = True
mydf

Name  Age  Salary Country  mob_num Adult
zero      Sam   23    5365  Canada     98.0   NaN
one       Pam   34    6756     USA     98.0  True
two    Suresh   19    5392   India     34.0   NaN
three  Yasmin   31    5362    None     12.0  True
four    Gopal   36    8336  Mexico      NaN  True

In [336]:
mydf['Adult']= np.where(mydf.Age>30, True, False)
mydf

Name  Age  Salary Country  mob_num  Adult
zero      Sam   23    8383  Canada     98.0  False
one       Pam   34    7593     USA     98.0   True
two    Suresh   19    6121   India     34.0  False
three  Yasmin   31    6662    None     12.0   True
four    Gopal   36    6513  Mexico      NaN   True

In [ ]:
mydf['Adult'] = mydf['Age'].apply(lambda x: True if x > 30 else False)
mydf

Name  Age  Salary Country  mob_num  Adult
zero      Sam   23    5365  Canada     98.0  False
one       Pam   34    6756     USA     98.0   True
two    Suresh   19    5392   India     34.0  False
three  Yasmin   31    5362    None     12.0   True
four    Gopal   36    8336  Mexico      NaN   True

In [ ]:
%time
data['Pclass'] = data['Pclass'].apply(lambda x: 2 if x==2 else 0)
data

CPU times: total: 0 ns
Wall time: 0 ns


PassengerId  Survived  Pclass  \
0              1         0       0   
1              2         1       0   
2              3         1       0   
3              4         1       0   
4              5         0       0   
..           ...       ...     ...   
886          887         0       2   
887          888         1       0   
888          889         0       0   
889          890         1       0   
890          891         0       0   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
%time
np.where(data['Pclass']==2, 2, 0)
data

CPU times: total: 0 ns
Wall time: 0 ns


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [337]:
country_df = pd.DataFrame(data=['USA', 'India', 'Mexico'], columns=['country'])

pd.merge(left=mydf, right=country_df, left_on='Country', right_on='country', how='inner')

Name  Age  Salary Country  mob_num  Adult country
0     Pam   34    7593     USA     98.0   True     USA
1  Suresh   19    6121   India     34.0  False   India
2   Gopal   36    6513  Mexico      NaN   True  Mexico

In [338]:
# at and iat used for fetching single element in df
mydf.at['one','Name']

'Pam'

In [339]:
mydf.iat[1,0]

'Pam'

In [340]:
mydf.reset_index(drop=True, inplace=True)

In [341]:
mydf[mydf.Age > 30]

Name  Age  Salary Country  mob_num  Adult
1     Pam   34    7593     USA     98.0   True
3  Yasmin   31    6662    None     12.0   True
4   Gopal   36    6513  Mexico      NaN   True

In [342]:
mydf['Salary_updated'] = np.where(mydf.Age > 30, mydf.Salary + 500, mydf.Salary)
mydf

Name  Age  Salary Country  mob_num  Adult  Salary_updated
0     Sam   23    8383  Canada     98.0  False            8383
1     Pam   34    7593     USA     98.0   True            8093
2  Suresh   19    6121   India     34.0  False            6121
3  Yasmin   31    6662    None     12.0   True            7162
4   Gopal   36    6513  Mexico      NaN   True            7013

In [343]:
countries = ['USA', 'India']

mydf[mydf.Country.isin(countries)]

Name  Age  Salary Country  mob_num  Adult  Salary_updated
1     Pam   34    7593     USA     98.0   True            8093
2  Suresh   19    6121   India     34.0  False            6121

In [344]:
mydf.drop(columns='Salary_updated', inplace=True)
mydf['Salary_updated']=np.where(mydf.Country.isin(countries),mydf.Salary + 500, mydf.Salary)
mydf

Name  Age  Salary Country  mob_num  Adult  Salary_updated
0     Sam   23    8383  Canada     98.0  False            8383
1     Pam   34    7593     USA     98.0   True            8093
2  Suresh   19    6121   India     34.0  False            6621
3  Yasmin   31    6662    None     12.0   True            6662
4   Gopal   36    6513  Mexico      NaN   True            6513

In [345]:
copy_df = mydf.copy()
copy_df

Name  Age  Salary Country  mob_num  Adult  Salary_updated
0     Sam   23    8383  Canada     98.0  False            8383
1     Pam   34    7593     USA     98.0   True            8093
2  Suresh   19    6121   India     34.0  False            6621
3  Yasmin   31    6662    None     12.0   True            6662
4   Gopal   36    6513  Mexico      NaN   True            6513

In [289]:
mydf.dropna(subset=['Country'], inplace=True)
mydf

Name  Age  Salary Country  mob_num  Adult  Salary_updated
0     Sam   23    5987  Canada     98.0  False            5987
1     Pam   34    8278     USA     98.0   True            8778
2  Suresh   19    8328   India     34.0  False            8828
4   Gopal   36    8130  Mexico      NaN   True            8130

In [346]:
mydf.Country.fillna(value='Sample', inplace=True)
mydf

Name  Age  Salary Country  mob_num  Adult  Salary_updated
0     Sam   23    8383  Canada     98.0  False            8383
1     Pam   34    7593     USA     98.0   True            8093
2  Suresh   19    6121   India     34.0  False            6621
3  Yasmin   31    6662  Sample     12.0   True            6662
4   Gopal   36    6513  Mexico      NaN   True            6513

In [360]:
mydf.mob_num = mydf.mob_num.fillna(value=np.mean(mydf['mob_num']))
mydf

Name  Age  Salary Country  mob_num  Adult  Salary_updated
0     Sam   23    8383  Canada     98.0  False            8383
1     Pam   34    7593     USA     98.0   True            8093
2  Suresh   19    6121   India     34.0  False            6621
3  Yasmin   31    6662  Sample     12.0   True            6662
4   Gopal   36    6513  Mexico     60.5   True            6513

In [361]:
myfunc = lambda x: x if x%2==0 else x*2
input_val = mydf['Salary']

mydf['Salary_updated'] = list(map(myfunc, input_val))
mydf

Name  Age  Salary Country  mob_num  Adult  Salary_updated
0     Sam   23    8383  Canada     98.0  False           16766
1     Pam   34    7593     USA     98.0   True           15186
2  Suresh   19    6121   India     34.0  False           12242
3  Yasmin   31    6662  Sample     12.0   True            6662
4   Gopal   36    6513  Mexico     60.5   True           13026